---
- name: Listen for events from GitHub
  hosts: all
  sources:
    - name: Listen to default webhook messages on port 5001
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Merge To Test Operation
      condition: >
        event.payload.action == "closed" and
        event.payload.pull_request.merged == true and
        event.payload.pull_request.base.ref == "test"
      action:
        run_workflow_template:
          organization: "build"
          name: "01-test_tenant_code_push_pipeline"
          job_args:
            extra_vars:
              "remote_branch": "test"
              "remote_repo": "{{ event.payload.repository.html_url }}"
    - name: Merge To PreProd Operation
      condition: >
        event.payload.action == "closed" and
        event.payload.pull_request.merged == true and
        event.payload.pull_request.base.ref == "preprod"
      action:
        run_workflow_template:
          organization: "build"
          name: "02-preprod_tenant_code_push_pipeline"
          job_args:
            extra_vars:
              "remote_branch": "preprod"
              "remote_repo": "{{ event.payload.repository.html_url }}"
    - name: Merge To Prod Operation
      condition: >
        event.payload.action == "closed" and
        event.payload.pull_request.merged == true and
        event.payload.pull_request.base.ref == "prod"
      action:
        run_workflow_template:
          organization: "build"
          name: "03-prod_tenant_code_push_pipeline"
          job_args:
            extra_vars:
              "remote_branch": "prod"
              "remote_repo": "{{ event.payload.repository.html_url }}"
    - name: Push To Dev Operation
      condition: >
        event.payload.pusher is defined and
        event.payload.ref != "refs/heads/test" and
        event.payload.ref != "refs/heads/preprod" and
        event.payload.ref != "refs/heads/prod"
      action:
        run_workflow_template:
          organization: "build"
          name: "test_tenant_code"
          job_args:
            extra_vars:
              "remote_branch": "{{ event.payload.ref.split('/')[2] }}"
              "remote_repo": "{{ event.payload.repository.html_url }}"

    # NOTE: This is commented out as it results in a lot of debug
    # in your activation log. But it can give you the full details
    # of the event structure being sent
    - name: Default debug
      condition: event.payload is defined
      actions:
        - debug:
            var: event.payload
