---
- name: Sign the supplied code repo with a key injected through credentials
  hosts: all
  gather_facts: true
  vars:
    remote_repo: "something"
    remote_branch: "dev"
    working_dir: "/tmp/working"

  tasks:
    - name: Collect the filename in a variable
      ansible.builtin.set_fact:
        key_file: "{{ lookup('ansible.builtin.env', 'GPG_PRIVATE_KEY_FILE') }}"

    - name: Collect the passphrase in a variable
      ansible.builtin.set_fact:
        passphrase: "{{ lookup('ansible.builtin.env', 'GPG_PASSPHRASE') }}"

    - name: Collect the Github token in a variable
      ansible.builtin.set_fact:
        github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_PAT') }}"

    - name: Calculate a signing branch name
      ansible.builtin.set_fact:
        merge_branch: "ansible-signed-{{ remote_branch }}-{{ ansible_facts['date_time']['iso8601_basic_short'] }}"

    - name: Debug the branch name
      ansible.builtin.debug:
        msg: "The merge branch name is {{ merge_branch }}"

    - name: Add the signing key to the keyring
      ansible.builtin.command:
        cmd: 'gpg --batch --yes --allow-secret-key-import --pinentry-mode loopback --passphrase "{{ passphrase }}" --import {{ key_file }}'
      changed_when: false
      register: __import_output
      ignore_errors: true

    - name: Debug the response
      ansible.builtin.debug:
        var: __import_output

    - name: Retrieve the repo
      ansible.scm.git_retrieve:
        branch:
          name: "{{ merge_branch }}"
        origin:
          url: "{{ remote_repo }}"
          token: "{{ github_token }}"
        upstream:
          url: "{{ remote_repo }}"
        parent_directory: "{{ working_dir }}"
      register: __git_receive_output

    - name: Set repo directory
      ansible.builtin.set_fact:
        repo_dir: "{{ __git_receive_output.path }}"

    - name: Check for the manifest file
      ansible.builtin.stat:
        path: "{{ repo_dir }}/MANIFEST.in"
      register: __manifest_file

    - name: Fail if no manifest file is found
      ansible.builtin.fail:
        msg: "No MANIFEST.in file found in the root of the repository. This is required for ansible-sign to work."
      when: not __manifest_file.stat.exists

    - name: Run ansible-sign
      ansible.builtin.command:
        cmd: "ansible-sign --debug project gpg-sign ."
        chdir: "{{ repo_dir }}"
      environment:
        ANSIBLE_SIGN_GPG_PASSPHRASE: "{{ passphrase }}"
      changed_when: false
      register: __ansible_sign_output
      ignore_errors: true

    - name: Debug the response
      ansible.builtin.debug:
        var: __ansible_sign_output

    - name: Update the build_log summary
      ansible.builtin.set_fact:
        build_log: "{{ __ansible_sign_output }} ~ {{ build_log | default('') }}"

    - name: Validate the response
      ansible.builtin.fail:
        msg: ansible-sign for Ansible code branch failed
      when: __ansible_sign_output.rc != 0

    - name: Publish the ansible-signing files back to the repo
      ansible.scm.git_publish:
        commit:
          message: "Build Pipeline: Signed the code with ansible-sign"
        path: "{{ repo_dir }}"
        token: "{{ github_token }}"
        user:
          name: "AAP Build Pipeline"
          email: "ansible@localhost"
