---
- name: Setup Pipeline Configuration in AAP
  hosts: all
  gather_facts: false

  tasks:
    - name: Load the AAP definition files
      ansible.builtin.include_vars:
        dir: "../aap_configuration/vars"
        extensions:
          - 'yml'
          - 'yaml'

    - name: Run deployment
      ansible.builtin.include_role:
        name: "infra.aap_configuration.dispatch"

    - name: Setup access token for webhooks
      ansible.controller.token:
        controller_host: "{{ aap_hostname }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        validate_certs: "{{ aap_validate_certs | default(true) }}"
        description: "Webhook Pipeline Access Token"
        scope: "write"
        application: "build_pipelines"
        state: present
      register: controller_oauthtoken

    - name: Store that token for later
      ansible.builtin.set_fact:
        pipeline_token: "{{ controller_oauthtoken.ansible_facts.controller_token.token }}"

    - name: Write out the new token value
      ansible.builtin.debug:
        msg: "Access token for pipeline access to AAP: {{ pipeline_token }}"
