---
- name: Setup Pipeline Configuration in AAP
  hosts: all
  gather_facts: false

  tasks:
    - name: Load the AAP definition files
      ansible.builtin.include_vars:
        dir: "../aap_configuration/vars"
        extensions:
          - 'yml'
          - 'yaml'

    - name: Run deployment
      ansible.builtin.include_role:
        name: "infra.aap_configuration.dispatch"
